name: Windows vcpkg Workflow

on:
  # direct pushes to protected branches are not supported
  pull_request:
  # run every day, at 2am UTC
  schedule:
    - cron: '0 2 * * *'
  # allow manually starting this workflow
  workflow_dispatch:

jobs:
  build:
    name: 'Windows vcpkg job'
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    # Restore from cache the previously built ports. If "cache miss" then provision vcpkg,
    # install desired ports, finally cache everything for the next run.
    - name: Restore from cache and run vcpkg
      uses: lukka/run-vcpkg@v5
      with:
        vcpkgArguments: '--triplet x64-windows poco'
        # Commit corresponding to vcpkg's master branch on 2020-11-20.
        vcpkgGitCommitId: e803bf11296d8e7900dafb41e7b1224778d33dc6
        # Workaround for https://github.com/ros-industrial/abb_libegm/pull/101#discussion_r433370614.
        # This line can be removed once Poco is linked via its imported CMake targets.
        vcpkgDirectory: '${{ github.workspace }}/../vcpkg'

    - name: Configure the project
      shell: bash
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_TOOLCHAIN_FILE=${VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake ..
        cmake --build . --config RelWithDebInfo
        cmake --install . --config RelWithDebInfo
